config/routes.rb
Rails.application.routes.draw do
  resources :links, only: %i[create show update destroy], param: :slug
  get '/:slug', to: "links#index"

  namespace :admin do
    resources :links, only: %i[index destroy], param: :slug do
      delete 'destroy_old', on: :collection
    end
  end
end

app/models/link.rb
# MongoDB is often chosen for URL shortener services due to its excellent scalability and performance.
# It handles high traffic and data growth efficiently through horizontal scaling, and offers fast read performance,
# crucial for quickly retrieving original URLs from shortened ones.
# This combination of easy scalability and speed makes it a suitable choice for high-traffic,
# data-intensive applications.

class Link
  include Mongoid::Document
  include Mongoid::Timestamps

  field :view_count, type: Integer, default: 0
  field :password_digest, type: String
  field :original_url, type: String
  field :slug, type: String

  validates :original_url, presence: true, format: { with: URI.regexp }
  validates :slug, uniqueness: true, presence: true
  validates :password_digest, presence: true

  index({ slug: 1 }, { unique: true })

  before_validation :generate_unique_slug

  # If a link has not been visited, it's not being updated.
  def self.delete_old_links(duration = 2)
    threshold_time = duration.to_i.months.ago
    where(:updated_at.lt => threshold_time).destroy_all
  end

  def self.search(term)
    regex = /#{Regexp.escape(term)}/i
    any_of({ slug: regex }, { original_url: regex })
  end

  def increment_view!
    update(view_count: view_count + 1)
  end

  def authenticate(password)
    BCrypt::Password.new(password_digest) == password if password_digest.present?
  end

  private

  def generate_unique_slug
    return if slug

    loop do
      self.slug = generate_random_slug
      break unless Link.where(slug: self.slug).exists?
    end
  end

  def generate_random_slug
    SecureRandom.urlsafe_base64(4)
  end

  def password=(new_password)
    self.password_digest = BCrypt::Password.create(new_password) if new_password.present?
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    # TODO: set up with ENV["BASIC_AUTH_NAME"] & ENV["BASIC_AUTH_PASSWORD"]
    http_basic_authenticate_with name: "1", password: "1"

    layout "admin_dashboard"
  end
end

app/controllers/admin/links_controller.rb
class Admin::LinksController < Admin::ApplicationController
  def index
    @links = Link.page(params[:page]).per(10)
    @links = @links.search(params[:search]) if params[:search]
  end

  def destroy
    @link = Link.find_by!(slug: params[:slug])

    if @link.destroy
      redirect_to admin_links_path, notice: 'The user has been deleted'
    else
      redirect_to :back, alert: @link.errors.full_messages.join(', ')
    end
  end

  def destroy_old
    Link.delete_old_links(params[:duration] || 2)

    redirect_to admin_links_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Mongoid::Errors::DocumentNotFound, with: :render_404

  private

  def render_404
    head :not_found
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :fetch_link, only: %i[index show update destroy]
  before_action :authorize!, only: %i[update destroy]

  def index
    @link.increment_view! # TODO: make it async in batches

    redirect_to @link.original_url, allow_other_host: true
  end

  def show
    render json: LinkSerializer.new(@link), status: :ok
  end

  def create
    link = Link.new(link_params)

    if link.save
      render json: LinkSerializer.new(link), status: :created
    else
      render json: ErrorSerializer.new(link), status: :unprocessable_entity
    end
  end

  def update
    if @link.update(link_params)
      render json: LinkSerializer.new(@link), status: :created
    else
      render json: ErrorSerializer.new(@link), status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy!

    head :ok
  end

  private

  def fetch_link
    @link = Link.find_by!(slug: params[:slug])
  end

  def link_params
    params.permit(:original_url, :password)
  end

  def authorize!
    head :unauthorized unless @link.authenticate(params[:password])
  end
end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/admin/common/_flash.haml
- if flash[:notice].present?
  .alert.alert-primary{role: "alert"}
    .container
      = flash[:notice]

- if flash[:alert].present?
  .alert.alert-danger{role: "alert"}
    .container
      = flash[:alert]

app/views/admin/links/index.html.haml
.container.mx-auto.justify-content-center.mt-3
  = form_tag('', method: :get, class: 'd-flex mb-2') do
    = text_field_tag(:search, params[:search], class: 'form-control me-2', placeholder: 'Search among original_url and slug', aria: {label: 'Search'})
    = submit_tag('Search', class: 'btn btn-outline-success', type: 'submit')
  = button_to "Destroy Old", destroy_old_admin_links_path(duration: 2), class: "btn btn-danger", method: :delete, data: {turbo_confirm: 'Are you sure you want to delete the links? Cant be reversed'}

.container.mx-auto.justify-content-center.align-items-center
  %table.table.table-fixed.table-bordered.table-striped
    %thead
      %tr
        %th ID
        %th Slug
        %th View Count
        %th original_url
        %th Created At
        %th Updated At
        %th Actions

    %tbody
      - @links.each do |link|
        %tr
          %td= link.id
          %td= link.slug
          %td= link.view_count
          %td= link_to link.original_url.truncate(30), link.original_url
          %td= l link.created_at, format: :short, locale: :en
          %td= l link.updated_at, format: :short, locale: :en
          %td
            .d-flex.flex-row
              = button_to "Delete", admin_link_path(link.slug), class: "btn btn-danger", style: 'margin-left: 10px', method: :delete, data: {turbo_confirm: 'Are you sure you want to delete the link? Cant be reversed'}

    %tfoot
      %tr
        %td{ colspan: 6 }
          = paginate @links

app/views/layouts/admin_dashboard.html.haml
<!doctype html>
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}

    = stylesheet_link_tag "admin_dashboard", "data-turbo-track": "reload"
    = javascript_importmap_tags "admin_dashboard"

    -# bootstrap 5
    %link{crossorigin: "anonymous", href: "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", integrity: "sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3", rel: "stylesheet"}/
    %script{crossorigin: "anonymous", integrity: "sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p", src: "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"}
  %body
    = render "admin/common/flash"
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>